name: Deploy UltraEdit Web

on:
  push:
    branches:
      - main  # Trigger only when pushing to main
  workflow_dispatch:  # Also allow manual runs from GitHub UI

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload website files
        uses: actions/upload-pages-artifact@v3
        with:
          path: .  # Upload everything in current directory (your HTML, CSS, JS)

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4


  

